/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MdcButtonProps,
} from './components/mdc-button';
import {
  MdcCardProps,
} from './components/mdc-card';
import {
  MdcCardMediaProps,
} from './components/mdc-card-media';
import {
  MdcCheckboxProps,
} from './components/mdc-checkbox';
import {
  MdcIconButtonProps,
} from './components/mdc-icon-button/index';
import {
  MDCIconButtonToggle,
} from '@material/icon-button';
import {
  MDCRipple,
} from '@material/ripple';
import {
  MdcLayoutGridProps,
} from './components/mdc-layout-grid';
import {
  MdcLayoutGridCellProps,
} from './components/mdc-layout-grid-cell';
import {
  MdcSelectProps,
} from './components/mdc-select';
import {
  MdcSwitchProps,
} from './components/mdc-switch/index';
import {
  MdcTextFieldProps,
} from './components/mdc-text-field';

export namespace Components {
  interface MdcButton {
    /**
    * Makes the button text and container slightly smaller.
    */
    'dense': MdcButtonProps["dense"];
    /**
    * Disabled buttons cannot be interacted with and have no visual interaction effect.
    */
    'disabled': MdcButtonProps["disabled"];
    /**
    * Icon to display, and aria-label value when label is not defined.
    */
    'icon': MdcButtonProps["icon"];
    /**
    * Label to display for the button, and aria-label.
    */
    'label': MdcButtonProps["label"];
    /**
    * Creates an outlined button that is flush with the surface.
    */
    'outlined': MdcButtonProps["outlined"];
    /**
    * Creates a contained button that is elevated above the surface.
    */
    'raised': MdcButtonProps["raised"];
    /**
    * When true, icon will be displayed after label.
    */
    'trailingIcon': MdcButtonProps["trailingIcon"];
    /**
    * Creates a contained button that is flush with the surface.
    */
    'unelevated': MdcButtonProps["unelevated"];
  }
  interface MdcCard {
    'outlined': MdcCardProps["outlined"];
  }
  interface MdcCardActionButtons {}
  interface MdcCardActionIcons {}
  interface MdcCardActions {}
  interface MdcCardMedia {
    'imageUrl': MdcCardMediaProps["imageUrl"];
    'size': MdcCardMediaProps["size"];
  }
  interface MdcCardMediaContent {}
  interface MdcCardPrimaryContent {}
  interface MdcCheckbox {
    'checked': MdcCheckboxProps['checked'];
    'disabled': MdcCheckboxProps['disabled'];
    'indeterminate': MdcCheckboxProps['indeterminate'];
    'layout': () => Promise<void>;
    'name': MdcCheckboxProps['name'];
    'value': MdcCheckboxProps['value'];
  }
  interface MdcChipSet {
    'addChip': (chipEl: HTMLElement) => Promise<void>;
  }
  interface MdcDialog {
    'close': (action: string) => Promise<void>;
    'isOpen': () => Promise<boolean>;
    'layout': () => Promise<void>;
    'open': () => Promise<void>;
    'surface': HTMLElement | HTMLElement[];
  }
  interface MdcIconButton {
    'checked': MdcIconButtonProps['checked'];
    'disabled': MdcIconButtonProps['disabled'];
    'layout': () => Promise<void>;
    'name': MdcIconButtonProps['name'];
    'on': boolean;
    'toggle': boolean;
    'type': MdcIconButtonProps['type'];
    'value': MdcIconButtonProps['value'];
  }
  interface MdcLayoutGrid {
    /**
    * The grid is by default center aligned. You can align left or right to change this behavior. Note, this will have no effect when the grid already fills its container.
    */
    'align': MdcLayoutGridProps["align"];
    /**
    * You can designate each column to have a certain width by setting fixedColumnWidth. The column width can be specified through css custom properties `--mdc-layout-grid-column-width-{screen_size}.` The column width is set to 72px on all devices by default.
    */
    'fixedColumn': MdcLayoutGridProps["fixedColumnWidth"];
  }
  interface MdcLayoutGridCell {
    'align'?: MdcLayoutGridCellProps["align"];
    'columns'?: MdcLayoutGridCellProps["columns"];
    'desktopColumns'?: MdcLayoutGridCellProps["desktopColumns"];
    'order'?: MdcLayoutGridCellProps["order"];
    'phoneColumns'?: MdcLayoutGridCellProps["phoneColumns"];
    'tabletColumns'?: MdcLayoutGridCellProps["tabletColumns"];
  }
  interface MdcLayoutGridRow {}
  interface MdcLinearProgress {
    'close': () => Promise<void>;
    'getBuffer': () => Promise<number>;
    'getDeterminate': () => Promise<boolean>;
    'getProgress': () => Promise<number>;
    'getReverse': () => Promise<boolean>;
    'open': () => Promise<void>;
    'setBuffer': (value: number) => Promise<void>;
    'setDeterminate': (value: boolean) => Promise<void>;
    'setProgress': (value: number) => Promise<void>;
    'setReverse': (value: boolean) => Promise<void>;
  }
  interface MdcSelect {
    'disabled': MdcSelectProps['disabled'];
    'getDisabled': () => Promise<boolean>;
    'getValid': () => Promise<boolean>;
    'getValue': () => Promise<string>;
    'label': MdcSelectProps['label'];
    'layout': () => Promise<void>;
    'name': MdcSelectProps['name'];
    'outlined': MdcSelectProps['outlined'];
    'required': MdcSelectProps['required'];
    'selected': MdcSelectProps['selected'];
    'setDisabled': (disabled?: boolean) => Promise<void>;
    'setValid': (valid: boolean) => Promise<boolean>;
    'setValue': (value: string) => Promise<void>;
  }
  interface MdcSnackbar {
    'close': (action: string) => Promise<void>;
    'getActionButtonText': () => Promise<string>;
    'getCloseOnEscape': () => Promise<boolean>;
    'getLabelText': () => Promise<string>;
    'getTimeoutMs': () => Promise<number>;
    'isOpen': () => Promise<boolean>;
    'open': () => Promise<void>;
    'setActionButtonText': (text: string) => Promise<void>;
    'setCloseOnEscape': (closes: boolean) => Promise<void>;
    'setLabelText': (text: string) => Promise<void>;
    'setTimeoutMs': (ms: number) => Promise<void>;
  }
  interface MdcSwitch {
    'checked': MdcSwitchProps['checked'];
    'disabled': MdcSwitchProps['disabled'];
    'name': MdcSwitchProps['name'];
    'setChecked': (checked?: boolean) => Promise<void>;
    'setDisabled': (disabled?: boolean) => Promise<void>;
  }
  interface MdcTextField {
    'cols': MdcTextFieldProps['cols'];
    'disabled': MdcTextFieldProps['disabled'];
    'focusNative': () => Promise<void>;
    'fullWidth': MdcTextFieldProps['fullWidth'];
    'getDisabled': () => Promise<boolean>;
    'getValid': () => Promise<boolean>;
    'getValue': () => Promise<string>;
    'inputRef': MdcTextFieldProps['inputRef'];
    'label': MdcTextFieldProps['label'];
    'layout': () => Promise<void>;
    'name': MdcTextFieldProps['name'];
    'outlined': MdcTextFieldProps['outlined'];
    'required': MdcTextFieldProps['required'];
    'rows': MdcTextFieldProps['rows'];
    'setDisabled': (disabled?: boolean) => Promise<void>;
    'setValid': (valid: boolean) => Promise<boolean>;
    'setValue': (value: string) => Promise<void>;
    'textarea': MdcTextFieldProps['textarea'];
    'type': MdcTextFieldProps['type'];
    'value': MdcTextFieldProps['value'];
    'withLeadingIcon': MdcTextFieldProps['withLeadingIcon'];
    'withTrailingIcon': MdcTextFieldProps['withTrailingIcon'];
  }
}

declare global {


  interface HTMLMdcButtonElement extends Components.MdcButton, HTMLStencilElement {}
  var HTMLMdcButtonElement: {
    prototype: HTMLMdcButtonElement;
    new (): HTMLMdcButtonElement;
  };

  interface HTMLMdcCardElement extends Components.MdcCard, HTMLStencilElement {}
  var HTMLMdcCardElement: {
    prototype: HTMLMdcCardElement;
    new (): HTMLMdcCardElement;
  };

  interface HTMLMdcCardActionButtonsElement extends Components.MdcCardActionButtons, HTMLStencilElement {}
  var HTMLMdcCardActionButtonsElement: {
    prototype: HTMLMdcCardActionButtonsElement;
    new (): HTMLMdcCardActionButtonsElement;
  };

  interface HTMLMdcCardActionIconsElement extends Components.MdcCardActionIcons, HTMLStencilElement {}
  var HTMLMdcCardActionIconsElement: {
    prototype: HTMLMdcCardActionIconsElement;
    new (): HTMLMdcCardActionIconsElement;
  };

  interface HTMLMdcCardActionsElement extends Components.MdcCardActions, HTMLStencilElement {}
  var HTMLMdcCardActionsElement: {
    prototype: HTMLMdcCardActionsElement;
    new (): HTMLMdcCardActionsElement;
  };

  interface HTMLMdcCardMediaElement extends Components.MdcCardMedia, HTMLStencilElement {}
  var HTMLMdcCardMediaElement: {
    prototype: HTMLMdcCardMediaElement;
    new (): HTMLMdcCardMediaElement;
  };

  interface HTMLMdcCardMediaContentElement extends Components.MdcCardMediaContent, HTMLStencilElement {}
  var HTMLMdcCardMediaContentElement: {
    prototype: HTMLMdcCardMediaContentElement;
    new (): HTMLMdcCardMediaContentElement;
  };

  interface HTMLMdcCardPrimaryContentElement extends Components.MdcCardPrimaryContent, HTMLStencilElement {}
  var HTMLMdcCardPrimaryContentElement: {
    prototype: HTMLMdcCardPrimaryContentElement;
    new (): HTMLMdcCardPrimaryContentElement;
  };

  interface HTMLMdcCheckboxElement extends Components.MdcCheckbox, HTMLStencilElement {}
  var HTMLMdcCheckboxElement: {
    prototype: HTMLMdcCheckboxElement;
    new (): HTMLMdcCheckboxElement;
  };

  interface HTMLMdcChipSetElement extends Components.MdcChipSet, HTMLStencilElement {}
  var HTMLMdcChipSetElement: {
    prototype: HTMLMdcChipSetElement;
    new (): HTMLMdcChipSetElement;
  };

  interface HTMLMdcDialogElement extends Components.MdcDialog, HTMLStencilElement {}
  var HTMLMdcDialogElement: {
    prototype: HTMLMdcDialogElement;
    new (): HTMLMdcDialogElement;
  };

  interface HTMLMdcIconButtonElement extends Components.MdcIconButton, HTMLStencilElement {}
  var HTMLMdcIconButtonElement: {
    prototype: HTMLMdcIconButtonElement;
    new (): HTMLMdcIconButtonElement;
  };

  interface HTMLMdcLayoutGridElement extends Components.MdcLayoutGrid, HTMLStencilElement {}
  var HTMLMdcLayoutGridElement: {
    prototype: HTMLMdcLayoutGridElement;
    new (): HTMLMdcLayoutGridElement;
  };

  interface HTMLMdcLayoutGridCellElement extends Components.MdcLayoutGridCell, HTMLStencilElement {}
  var HTMLMdcLayoutGridCellElement: {
    prototype: HTMLMdcLayoutGridCellElement;
    new (): HTMLMdcLayoutGridCellElement;
  };

  interface HTMLMdcLayoutGridRowElement extends Components.MdcLayoutGridRow, HTMLStencilElement {}
  var HTMLMdcLayoutGridRowElement: {
    prototype: HTMLMdcLayoutGridRowElement;
    new (): HTMLMdcLayoutGridRowElement;
  };

  interface HTMLMdcLinearProgressElement extends Components.MdcLinearProgress, HTMLStencilElement {}
  var HTMLMdcLinearProgressElement: {
    prototype: HTMLMdcLinearProgressElement;
    new (): HTMLMdcLinearProgressElement;
  };

  interface HTMLMdcSelectElement extends Components.MdcSelect, HTMLStencilElement {}
  var HTMLMdcSelectElement: {
    prototype: HTMLMdcSelectElement;
    new (): HTMLMdcSelectElement;
  };

  interface HTMLMdcSnackbarElement extends Components.MdcSnackbar, HTMLStencilElement {}
  var HTMLMdcSnackbarElement: {
    prototype: HTMLMdcSnackbarElement;
    new (): HTMLMdcSnackbarElement;
  };

  interface HTMLMdcSwitchElement extends Components.MdcSwitch, HTMLStencilElement {}
  var HTMLMdcSwitchElement: {
    prototype: HTMLMdcSwitchElement;
    new (): HTMLMdcSwitchElement;
  };

  interface HTMLMdcTextFieldElement extends Components.MdcTextField, HTMLStencilElement {}
  var HTMLMdcTextFieldElement: {
    prototype: HTMLMdcTextFieldElement;
    new (): HTMLMdcTextFieldElement;
  };
  interface HTMLElementTagNameMap {
    'mdc-button': HTMLMdcButtonElement;
    'mdc-card': HTMLMdcCardElement;
    'mdc-card-action-buttons': HTMLMdcCardActionButtonsElement;
    'mdc-card-action-icons': HTMLMdcCardActionIconsElement;
    'mdc-card-actions': HTMLMdcCardActionsElement;
    'mdc-card-media': HTMLMdcCardMediaElement;
    'mdc-card-media-content': HTMLMdcCardMediaContentElement;
    'mdc-card-primary-content': HTMLMdcCardPrimaryContentElement;
    'mdc-checkbox': HTMLMdcCheckboxElement;
    'mdc-chip-set': HTMLMdcChipSetElement;
    'mdc-dialog': HTMLMdcDialogElement;
    'mdc-icon-button': HTMLMdcIconButtonElement;
    'mdc-layout-grid': HTMLMdcLayoutGridElement;
    'mdc-layout-grid-cell': HTMLMdcLayoutGridCellElement;
    'mdc-layout-grid-row': HTMLMdcLayoutGridRowElement;
    'mdc-linear-progress': HTMLMdcLinearProgressElement;
    'mdc-select': HTMLMdcSelectElement;
    'mdc-snackbar': HTMLMdcSnackbarElement;
    'mdc-switch': HTMLMdcSwitchElement;
    'mdc-text-field': HTMLMdcTextFieldElement;
  }
}

declare namespace LocalJSX {
  interface MdcButton {
    /**
    * Makes the button text and container slightly smaller.
    */
    'dense'?: MdcButtonProps["dense"];
    /**
    * Disabled buttons cannot be interacted with and have no visual interaction effect.
    */
    'disabled'?: MdcButtonProps["disabled"];
    /**
    * Icon to display, and aria-label value when label is not defined.
    */
    'icon'?: MdcButtonProps["icon"];
    /**
    * Label to display for the button, and aria-label.
    */
    'label'?: MdcButtonProps["label"];
    /**
    * Creates an outlined button that is flush with the surface.
    */
    'outlined'?: MdcButtonProps["outlined"];
    /**
    * Creates a contained button that is elevated above the surface.
    */
    'raised'?: MdcButtonProps["raised"];
    /**
    * When true, icon will be displayed after label.
    */
    'trailingIcon'?: MdcButtonProps["trailingIcon"];
    /**
    * Creates a contained button that is flush with the surface.
    */
    'unelevated'?: MdcButtonProps["unelevated"];
  }
  interface MdcCard {
    'outlined'?: MdcCardProps["outlined"];
  }
  interface MdcCardActionButtons {}
  interface MdcCardActionIcons {}
  interface MdcCardActions {}
  interface MdcCardMedia {
    'imageUrl'?: MdcCardMediaProps["imageUrl"];
    'size'?: MdcCardMediaProps["size"];
  }
  interface MdcCardMediaContent {}
  interface MdcCardPrimaryContent {}
  interface MdcCheckbox {
    'checked'?: MdcCheckboxProps['checked'];
    'disabled'?: MdcCheckboxProps['disabled'];
    'indeterminate'?: MdcCheckboxProps['indeterminate'];
    'name'?: MdcCheckboxProps['name'];
    'value'?: MdcCheckboxProps['value'];
  }
  interface MdcChipSet {}
  interface MdcDialog {
    'surface': HTMLElement | HTMLElement[];
  }
  interface MdcIconButton {
    'checked'?: MdcIconButtonProps['checked'];
    'disabled'?: MdcIconButtonProps['disabled'];
    'name'?: MdcIconButtonProps['name'];
    'on'?: boolean;
    'toggle'?: boolean;
    'type'?: MdcIconButtonProps['type'];
    'value'?: MdcIconButtonProps['value'];
  }
  interface MdcLayoutGrid {
    /**
    * The grid is by default center aligned. You can align left or right to change this behavior. Note, this will have no effect when the grid already fills its container.
    */
    'align'?: MdcLayoutGridProps["align"];
    /**
    * You can designate each column to have a certain width by setting fixedColumnWidth. The column width can be specified through css custom properties `--mdc-layout-grid-column-width-{screen_size}.` The column width is set to 72px on all devices by default.
    */
    'fixedColumn'?: MdcLayoutGridProps["fixedColumnWidth"];
  }
  interface MdcLayoutGridCell {
    'align'?: MdcLayoutGridCellProps["align"];
    'columns'?: MdcLayoutGridCellProps["columns"];
    'desktopColumns'?: MdcLayoutGridCellProps["desktopColumns"];
    'order'?: MdcLayoutGridCellProps["order"];
    'phoneColumns'?: MdcLayoutGridCellProps["phoneColumns"];
    'tabletColumns'?: MdcLayoutGridCellProps["tabletColumns"];
  }
  interface MdcLayoutGridRow {}
  interface MdcLinearProgress {}
  interface MdcSelect {
    'disabled'?: MdcSelectProps['disabled'];
    'label'?: MdcSelectProps['label'];
    'name'?: MdcSelectProps['name'];
    'outlined'?: MdcSelectProps['outlined'];
    'required'?: MdcSelectProps['required'];
    'selected'?: MdcSelectProps['selected'];
  }
  interface MdcSnackbar {}
  interface MdcSwitch {
    'checked'?: MdcSwitchProps['checked'];
    'disabled'?: MdcSwitchProps['disabled'];
    'name'?: MdcSwitchProps['name'];
  }
  interface MdcTextField {
    'cols'?: MdcTextFieldProps['cols'];
    'disabled'?: MdcTextFieldProps['disabled'];
    'fullWidth'?: MdcTextFieldProps['fullWidth'];
    'inputRef'?: MdcTextFieldProps['inputRef'];
    'label'?: MdcTextFieldProps['label'];
    'name'?: MdcTextFieldProps['name'];
    'outlined'?: MdcTextFieldProps['outlined'];
    'required'?: MdcTextFieldProps['required'];
    'rows'?: MdcTextFieldProps['rows'];
    'textarea'?: MdcTextFieldProps['textarea'];
    'type'?: MdcTextFieldProps['type'];
    'value'?: MdcTextFieldProps['value'];
    'withLeadingIcon'?: MdcTextFieldProps['withLeadingIcon'];
    'withTrailingIcon'?: MdcTextFieldProps['withTrailingIcon'];
  }

  interface IntrinsicElements {
    'mdc-button': MdcButton;
    'mdc-card': MdcCard;
    'mdc-card-action-buttons': MdcCardActionButtons;
    'mdc-card-action-icons': MdcCardActionIcons;
    'mdc-card-actions': MdcCardActions;
    'mdc-card-media': MdcCardMedia;
    'mdc-card-media-content': MdcCardMediaContent;
    'mdc-card-primary-content': MdcCardPrimaryContent;
    'mdc-checkbox': MdcCheckbox;
    'mdc-chip-set': MdcChipSet;
    'mdc-dialog': MdcDialog;
    'mdc-icon-button': MdcIconButton;
    'mdc-layout-grid': MdcLayoutGrid;
    'mdc-layout-grid-cell': MdcLayoutGridCell;
    'mdc-layout-grid-row': MdcLayoutGridRow;
    'mdc-linear-progress': MdcLinearProgress;
    'mdc-select': MdcSelect;
    'mdc-snackbar': MdcSnackbar;
    'mdc-switch': MdcSwitch;
    'mdc-text-field': MdcTextField;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mdc-button': LocalJSX.MdcButton & JSXBase.HTMLAttributes<HTMLMdcButtonElement>;
      'mdc-card': LocalJSX.MdcCard & JSXBase.HTMLAttributes<HTMLMdcCardElement>;
      'mdc-card-action-buttons': LocalJSX.MdcCardActionButtons & JSXBase.HTMLAttributes<HTMLMdcCardActionButtonsElement>;
      'mdc-card-action-icons': LocalJSX.MdcCardActionIcons & JSXBase.HTMLAttributes<HTMLMdcCardActionIconsElement>;
      'mdc-card-actions': LocalJSX.MdcCardActions & JSXBase.HTMLAttributes<HTMLMdcCardActionsElement>;
      'mdc-card-media': LocalJSX.MdcCardMedia & JSXBase.HTMLAttributes<HTMLMdcCardMediaElement>;
      'mdc-card-media-content': LocalJSX.MdcCardMediaContent & JSXBase.HTMLAttributes<HTMLMdcCardMediaContentElement>;
      'mdc-card-primary-content': LocalJSX.MdcCardPrimaryContent & JSXBase.HTMLAttributes<HTMLMdcCardPrimaryContentElement>;
      'mdc-checkbox': LocalJSX.MdcCheckbox & JSXBase.HTMLAttributes<HTMLMdcCheckboxElement>;
      'mdc-chip-set': LocalJSX.MdcChipSet & JSXBase.HTMLAttributes<HTMLMdcChipSetElement>;
      'mdc-dialog': LocalJSX.MdcDialog & JSXBase.HTMLAttributes<HTMLMdcDialogElement>;
      'mdc-icon-button': LocalJSX.MdcIconButton & JSXBase.HTMLAttributes<HTMLMdcIconButtonElement>;
      'mdc-layout-grid': LocalJSX.MdcLayoutGrid & JSXBase.HTMLAttributes<HTMLMdcLayoutGridElement>;
      'mdc-layout-grid-cell': LocalJSX.MdcLayoutGridCell & JSXBase.HTMLAttributes<HTMLMdcLayoutGridCellElement>;
      'mdc-layout-grid-row': LocalJSX.MdcLayoutGridRow & JSXBase.HTMLAttributes<HTMLMdcLayoutGridRowElement>;
      'mdc-linear-progress': LocalJSX.MdcLinearProgress & JSXBase.HTMLAttributes<HTMLMdcLinearProgressElement>;
      'mdc-select': LocalJSX.MdcSelect & JSXBase.HTMLAttributes<HTMLMdcSelectElement>;
      'mdc-snackbar': LocalJSX.MdcSnackbar & JSXBase.HTMLAttributes<HTMLMdcSnackbarElement>;
      'mdc-switch': LocalJSX.MdcSwitch & JSXBase.HTMLAttributes<HTMLMdcSwitchElement>;
      'mdc-text-field': LocalJSX.MdcTextField & JSXBase.HTMLAttributes<HTMLMdcTextFieldElement>;
    }
  }
}


